COMBO_ENABLE = yes
WPM_ENABLE = yes          # Uses about 800 bytes (plus code to display on OLED)
LTO_ENABLE = yes
GRAVE_ESC_ENABLE = no    #Uses about 82 bytes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
SPACE_CADET_ENABLE = no
EXTRAKEY_ENABLE = no
#MAGIC_ENABLE = no

CAPS_WORD_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom

AVR_USE_MINIMAL_PRINTF = yes