#define PERMISSIVE_HOLD

#define ENABLE_COMPILE_KEYCODE

#ifdef MH_AUTO_BUTTONS
  #define MH_AUTO_BUTTONS_LAYER _MOUSE
  #define MH_AUTO_BUTTONS_TIMEOUT 650
  #define PS2_MOUSE_SCROLL_BTN_MASK 0 //(1<<PS2_MOUSE_BTN_MIDDLE) /* Default */
  #define PS2_MOUSE_SCROLL_BTN_SEND 1000 /* Default */
  #define PS2_MOUSE_SCROLL_DIVISOR_H 2
  #define PS2_MOUSE_SCROLL_DIVISOR_V 2
//  #define PS2_MOUSE_USE_REMOTE_MODE
#endif
