# MCU name
MCU = RP2040
BOOTLOADER = rp2040

CUSTOM_MATRIX = lite
SRC += matrix.c

SERIAL_DRIVER = vendor

POINTING_DEVICE_ENABLE = yes

POINTING_DEVICE_DRIVER = pimoroni_trackball

ifeq ($(strip $(POINTING_DEVICE_DRIVER)), pimoroni_trackball)
	OPT_DEFS += -DPOINTING_DEVICE_IS_PIMORONI
endif

ifeq ($(strip $(POINTING_DEVICE_DRIVER)), pmw3360)
	OPT_DEFS += -DPOINTING_DEVICE_IS_PMW3360
endif

ifeq ($(strip $(POINTING_DEVICE_DRIVER)), pmw3389)
	OPT_DEFS += -DPOINTING_DEVICE_IS_PMW3389
endif
