# MCU name
MCU = RP2040
BOOTLOADER = rp2040
BOARD = GENERIC_RP_RP2040

CUSTOM_MATRIX = lite
SRC += matrix.c

SERIAL_DRIVER = vendor
PS2_MOUSE_ENABLE = yes
MH_AUTO_BUTTONS = yes

ifeq ($(strip $(MH_AUTO_BUTTONS)), yes)
  OPT_DEFS += -DMH_AUTO_BUTTONS
endif
